### ISSUE TITLE
Phase 3

### ISSUE THREAD

**Issue by tramstheman** [North-Vine-Engineering/CST338_GUICards#7]
This ticket represents phase 3 of the game. I suggest we only begin on this ticket after phase 2 has been completed. This phase essentially consists of a driver which initializes the game engine defined in the card game framework class. This will require some minor refactoring.

**Comment by KyleLuoma** [comment]
I worked on my branch this evening / morning, but didn't make much progress as I couldn't figure out how to implement a game loop using the event based buttons in swing. 
I was also having some trouble trying to get what is displayed in-synch with the hands in the framework object. I wonder if having our listeners resident in our Main() class would simplify this a little bit so we can manipulate package private instances and variables without having to pass them to the adapter object. Just a thought.
